language: csharp
mono:
  - latest
  - 3.12.0
  - 2.10.8
solution: ICSharpCode.SharpZipLib.sln
#install:
#  - nuget restore ICSharpCode.SharpZipLib.sln
#  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ICSharpCode.SharpZipLib.sln
  - xbuild /p:Configuration=Release ICSharpCode.SharpZipLib.sln
#  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ICSharpCode.SharpZipLib.Tests/bin/Release/ICSharpCode.SharpZipLib.Tests.dll
