language: csharp
mono:
  - latest
os:
  - linux
  - osx
solution: ICSharpCode.SharpZipLib.sln
install:
  - nuget restore ICSharpCode.SharpZipLib.sln
#  - nuget install NUnit.ConsoleRunner -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ICSharpCode.SharpZipLib.sln
  - xbuild /p:Configuration=Release ICSharpCode.SharpZipLib.sln
  - mono ./packages/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe /framework:mono-4.0 /runlist:./ICSharpCode.SharpZipLib.Tests/PassingTests.txt /result:./Documentation/nunit3-test-results-travis.xml ./bin/Release/ICSharpCode.SharpZipLib.Tests.dll
